SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/LogOnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SolicitudIntegralMVC.Infraestructure;
using SolicitudIntegralMVC.Infraestructure.Abstract;
using STPIntegral.Negocios;

namespace SolicitudIntegralMVC.Controllers
{
    [AllowAnonymous]
    public class LogOnController : Controller
    {
        //
        // GET: /LogOn/

        public LogOnController()
        {
        }

        public ActionResult Index()
        {
            SolicitudIntegralMVC.Models.UserLogonModel loginModel = new Models.UserLogonModel();

            loginModel.UsuarioDominio = ObtenerUsuarioDominio();

            Session["pre_login_user"] = loginModel;

            return View(loginModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult ValidarUsuarioPassword(SolicitudIntegralMVC.Models.UserLogonModel user_login)
        {
            if (STPIntegral.Negocios.Utilerias.ObtenerTipoTrabajador(user_login.UsuarioFormulario.NombreUsuario) == "PEMEX")
            {
                user_login.UsuarioFormulario.NombreUsuario = STPIntegral.Negocios.Utilerias.FormatearFichaRfc(user_login.UsuarioFormulario.NombreUsuario);
            }

            user_login.UsuarioDominio = ObtenerUsuarioDominio();
            user_login.UsuarioFormulario = ValidarUsuarioPassword(user_login.UsuarioFormulario.NombreUsuario, user_login.UsuarioFormulario.Password);

            if (user_login.UsuarioFormulario != null && user_login.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles != null && user_login.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Count <= 0)
            {
                TempData["mensaje_error"] = "Usuario o Contraseña incorrectos";
            }
            else
            {
                Session["pre_login_user"] = user_login;
            }


            return View("index",user_login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogInUsuarioFormulario(SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso)
        {
            ActionResult resultado = null;

            if (Session["pre_login_user"] != null)
            {
                SolicitudIntegralMVC.Models.UserLogonModel pre_login_user = Session["pre_login_user"] as SolicitudIntegralMVC.Models.UserLogonModel;

                if (pre_login_user != null && pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles != null && pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Any(x => x.IdPermisoUa == permiso.IdPermisoUa))
                {
                    FormsAuthentication.SetAuthCookie(pre_login_user.UsuarioFormulario.NombreUsuario, false);

                    SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso_actual = pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Single(x => x.IdPermisoUa == permiso.IdPermisoUa);

                    pre_login_user.UsuarioFormulario.NodoAtencionActual = String.IsNullOrEmpty(permiso_actual.NodoAtencion) || (!String.IsNullOrEmpty(permiso_actual.NodoAtencion) && permiso_actual.NodoAtencion.Trim() == "") ? "CME" : permiso_actual.NodoAtencion;
                    
                    pre_login_user.UsuarioFormulario.IdPermisoUaActual = permiso_actual.IdPermisoUa;
                    pre_login_user.UsuarioFormulario.IdDUsuarioActual = permiso_actual.IdDUsuario;
                    pre_login_user.UsuarioFormulario.IdMUsuarioActual = permiso_actual.IdMUsuario;

                    pre_login_user.UsuarioFormulario.PermisoUsuarioActual = permiso_actual.Permiso.Trim('[', ']');

                    pre_login_user.UsuarioFormulario.CveActivoActual = permiso_actual.CveActivo;
                    pre_login_user.UsuarioFormulario.CveRegionActual = permiso_actual.CveRegion;
                    pre_login_user.UsuarioFormulario.DescripcionActivoActual = permiso_actual.DescripcionActivo;
                    pre_login_user.UsuarioFormulario.DescripcionRegionActual = permiso_actual.DescripcionRegion;
                    pre_login_user.UsuarioFormulario.SubdivisionActual = permiso_actual.Subdivision;
                    pre_login_user.UsuarioFormulario.DescripcionSubdivisionActual = permiso_actual.DescripcionSubdivision;

                    if (String.IsNullOrEmpty(pre_login_user.UsuarioFormulario.NodoAtencionActual))
                    {
                        pre_login_user.UsuarioFormulario.NodoAtencionActual = "CME";
                    }

                    SolicitudIntegralMVC.Infraestructure.Utilerias.GuardarUsuarioAutentificado(this.HttpContext, pre_login_user.UsuarioFormulario);

                    SolicitudIntegralMVC.Infraestructure.Concrete.FormsAuthProvider authProvider = new Infraestructure.Concrete.FormsAuthProvider();
                    authProvider.Authenticate(pre_login_user.UsuarioFormulario.NombreUsuario, pre_login_user.UsuarioFormulario.Password);
                    
                    resultado = RedirectToAction("Index","Home");
                }
            }
            else
            {
                TempData["mensaje_error"] = "Ocurrio un error con el intento de acceder, por favor intentelo de nuevo";
                resultado = View("index");
            }

            return resultado;
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogInUsuarioDominio(SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso)
        {
            ActionResult resultado = null;

            if (Session["pre_login_user"] != null)
            {
                SolicitudIntegralMVC.Models.UserLogonModel pre_login_user = Session["pre_login_user"] as SolicitudIntegralMVC.Models.UserLogonModel;
                 
                if (pre_login_user != null && pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles != null && pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles.Any(x => x.IdPermisoUa == permiso.IdPermisoUa))
                {
                    FormsAuthentication.SetAuthCookie(pre_login_user.UsuarioDominio.NombreUsuario, false);

                    SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso_actual = pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles.First(x => x.IdPermisoUa == permiso.IdPermisoUa);

                    pre_login_user.UsuarioFormulario.NodoAtencionActual = String.IsNullOrEmpty(permiso_actual.NodoAtencion) || (!String.IsNullOrEmpty(permiso_actual.NodoAtencion) && permiso_actual.NodoAtencion.Trim() == "") ? "CME" : permiso_actual.NodoAtencion;

                    pre_login_user.UsuarioDominio.IdPermisoUaActual = permiso_actual.IdPermisoUa;
                    pre_login_user.UsuarioFormulario.IdDUsuarioActual = permiso_actual.IdDUsuario;
                    pre_login_user.UsuarioFormulario.IdMUsuarioActual = permiso_actual.IdMUsuario;

                    pre_login_user.UsuarioDominio.PermisoUsuarioActual = permiso_actual.Permiso.Trim('[', ']');

                    pre_login_user.UsuarioDominio.CveActivoActual = permiso_actual.CveActivo;
                    pre_login_user.UsuarioDominio.CveRegionActual = permiso_actual.CveRegion;
                    pre_login_user.UsuarioDominio.DescripcionActivoActual = permiso_actual.DescripcionActivo;
                    pre_login_user.UsuarioDominio.DescripcionRegionActual = permiso_actual.DescripcionRegion;
                    pre_login_user.UsuarioDominio.SubdivisionActual = permiso_actual.Subdivision;
                    pre_login_user.UsuarioDominio.DescripcionSubdivisionActual = permiso_actual.DescripcionSubdivision;
                    pre_login_user.UsuarioDominio.SiglasActivoActual = permiso_actual.SiglasActivo;
                    pre_login_user.UsuarioDominio.SiglasRegionActual = permiso_actual.SiglasRegion;

                    if (String.IsNullOrEmpty(pre_login_user.UsuarioFormulario.NodoAtencionActual))
                    {
                        pre_login_user.UsuarioFormulario.NodoAtencionActual = "CME";
                    }

                    SolicitudIntegralMVC.Infraestructure.Utilerias.GuardarUsuarioAutentificado(this.HttpContext, pre_login_user.UsuarioDominio);

                    SolicitudIntegralMVC.Infraestructure.Concrete.FormsAuthProvider authProvider = new Infraestructure.Concrete.FormsAuthProvider();

                    authProvider.Authenticate(pre_login_user.UsuarioDominio.NombreUsuario, pre_login_user.UsuarioDominio.Password);

                    resultado = RedirectToAction("Index", "Home");
                }
            }
            else
            {
                TempData["mensaje_error"] = "Ocurrio un error con el intento de acceder, por favor intentelo de nuevo";
                resultado = View("index");
            }

            return resultado;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult RelacionarCuentaUsuarioDominio()
        {
            return PartialView();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RelacionarCuentaUsuarioDominio(string dominio, string usuario, string password)
        {
            ActionResult resultado = null;

            try
            {
                SolicitudIntegralMVC.Models.UserLogon permiso = ValidarUsuarioPassword(usuario, password);

                if (permiso != null)
                {
                    STPIntegral.Negocios.UsuariosController.ActualizarNombreUsuarioDominio(permiso.IdMUsuarioActual, password, dominio);
                }
                else
                {
                    throw new ShowCaseException("Usuario o contraseña invalidos", null, TypeMessage.warning, "");
                }

                resultado = Json(new { result = "OK", mensaje = "La cuenta del dominio se asigno exitosamente." }, JsonRequestBehavior.AllowGet);
            }

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SolicitudIntegralMVC.Controllers
{
    public class NoticiasController : Controller
    {
        //
        // GET: /Noticias/

        public ActionResult ListadoNoticias()
        {
            IEnumerable<STPIntegral.Datos.stp_c_mensajes> listados_mensajes = STPIntegral.Negocios.MensajesController.ObtenerNoticiasActualesParaSolicitudIntegral();
            return PartialView(listados_mensajes);
        }

    }
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/LogOn/Index.cshtml
@model SolicitudIntegralMVC.Models.UserLogonModel
@{
	ViewBag.Title = "Solicitud Integral: Acceso a Usuarios";
	Layout = null;
}

<!DOCTYPE html>
<html lang="es-mx">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="icon" type="image/gif" href="@Url.Content("~/Content/images/favicon.gif")" />

	<title>@ViewBag.Title</title>
	
	<link href="@Url.Content("~/Content/modern.css")" rel="stylesheet" />
	<link href="@Url.Content("~/Content/modern-responsive.css")" rel="stylesheet" />

	<link href="@Url.Content("~/Content/estilos.css")" rel="stylesheet" />    
	<link href="@Url.Content("~/Content/themes/base/jquery-ui-1.8.16.custom.css")" rel="stylesheet" />
	<link href="@Url.Content("~/Content/metro-bootstrap.css")" rel="stylesheet" />
	<link href="@Url.Content("~/Content/themes/jquery.tagit.css")" rel="stylesheet" />
	
	<script type="text/javascript">var rootDir = "@Url.Content("~/")"; </script>
    <script type="text/javascript" data-main="@Url.Content("~/scripts/main")" src="@Url.Content("~/scripts/require-jquery.js")"></script>

</head>

<body>
	<div id="login-page" class="page">
		
		<div id="page-header">
            
            <img src="~/Content/images/layout/header-left.png"/>    
            
            <img style="float:right" src="~/Content/images/layout/header-right.png"/>
            
        </div>

		<div class="page-region">
  
			<div class="grid page-region-content">

                <label id="mensaje-version-navegador" class="border-color-red" style="display:none;">Este sistema requiere la version 9 del Internet Explorer, se detecto que su navegador es una version anterior, se recomienda actualizarlo para poder usar el sistema</label>
					
				<h2>Página de Acceso a usuarios</h2>

				@if (Model != null && Model.UsuarioDominio != null && !String.IsNullOrEmpty(Model.UsuarioDominio.NombreUsuarioDominio))
    { 
					<label>Su cuenta de usuario del dominio [@Request.LogonUserIdentity.Name]  cuenta con los siguientes permisos para el Sistema de Solicitudes Integrales. </label> 
					
					  <table class="striped bordered hovered">
						<thead>
							<tr>
								<th>Seleccionar</th>
								<th>Permiso</th>
								<th>Subdivision</th>
								<th>Region</th>
                                <th>Activo</th>
                                <th>Gerencia</th>
								<th>Nodo</th>
							</tr>
						</thead>
						<tbody>
						@foreach (SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso in Model.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles)
      { 
							<tr>
								<td>
									@using (Html.BeginForm("LogInUsuarioDominio", "LogOn"))
         {    
										<input type="hidden" name="IdPermisoUa" value="@permiso.IdPermisoUa" />
										<input type="submit" value="Acceder" />
         }
								</td>
								<td>@permiso.Permiso</td>
								<td>@permiso.Subdivision</td>
                                <td>
                                    <label>[@permiso.Subdivision.Substring(0,1)] - @permiso.DescripcionRegion</label><br />
								</td>
                                <td>
                                    <label>[@permiso.Subdivision.Substring(1,2)] - @permiso.DescripcionActivo</label><br />
								</td>
                                <td>
                                    <label>[@permiso.Subdivision.Substring(3,2)] - @permiso.DescripcionSubdivision</label>
								</td>
								<td>@permiso.NodoAtencion</td>
							</tr>
      }
						</tbody>
					</table>
    }
    else
    { 
                <a id="relacion-cuenta-dominio" href="#">Su cuenta de usuario del dominio de PEMEX [@Request.LogonUserIdentity.Name] no esta relacionada a ninguna cuenta de usuario del sistema, de clic aqui si desea relacionarlo.</a>
    }

                @if (Model != null && Model.UsuarioDominio != null && !String.IsNullOrEmpty(Model.UsuarioDominio.NombreUsuarioDominio))
                {
                    <label class="border-color-blue">Si desea acceder con otra cuenta de usuario entonces proporcione sus datos de acceso.</label>
                }


				@using (Html.BeginForm("ValidarUsuarioPassword", "LogOn"))
				{ 

				<div id="tipo-personal" class="row">

					<label class="span1">Usuario</label>
					<span class="input-control text span2">
						<input type="text" name="UsuarioFormulario.NombreUsuario" id="txtNombreUsuario" value="@Model.UsuarioFormulario.NombreUsuario" />
					</span>
					
				</div>

				<div class="row">

					<label class="span1">Password</label>
					<span class="input-control text span2">
						<input type="password" name="UsuarioFormulario.Password" id="Password" />
					</span>

				</div>

				<div class="row">

					<span class="span2"></span>
					<input type="submit" id="btnAcceder" value="Validar" />
					
				</div>
					
					if (TempData["mensaje_error"] != null && !String.IsNullOrEmpty(TempData["mensaje_error"].ToString()))
					{
				<div class="row">
					<label class="error">@TempData["mensaje_error"]</label>
				</div>
					}
					
				}
					
			</div>

			@if (Model != null && Model.UsuarioFormulario != null && Model.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles != null)
			{ 
				<label>Su cuenta de usuario cuenta con los siguientes permisos, favor de elegir alguno para continuar. </label> 
					
				<table class="striped bordered hovered">
					<caption>
						<label>Permisos del usuario: [ @Model.UsuarioFormulario.NombreUsuario ] @Model.UsuarioFormulario.NombreCompletoUsuario - >> @Model.UsuarioFormulario.NombreUsuarioDominio</label>
					</caption>
					<thead>
						<tr>
							<th>Seleccionar</th>
							<th>Permiso</th>
							<th>Subdivision</th>
							<th>Departamento</th>
							<th>Nodo</th>
						</tr>
					</thead>
					<tbody>
					@foreach (SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso in Model.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles)
					{ 
						<tr>
							<td>
								@using (Html.BeginForm("LogInUsuarioFormulario", "LogOn"))
								{    
									<input type="hidden" name="IdPermisoUa" value="@permiso.IdPermisoUa" />
									<input type="submit" value="Acceder" />
								}
							</td>
							<td>@permiso.Permiso</td>
							<td>@permiso.Subdivision</td>
							<td>
                                <div>
                                    <label>[@permiso.Subdivision.Substring(0,1)] - @permiso.DescripcionRegion</label><br />
                                    <label>[@permiso.Subdivision.Substring(1,2)] - @permiso.DescripcionActivo</label><br />
                                    <label>[@permiso.Subdivision.Substring(3,2)] - @permiso.DescripcionSubdivision</label>
                                </div>
							</td>
							<td>@permiso.NodoAtencion</td>
						</tr>
					}
					</tbody>
				</table>
			}
		</div>

		@Html.Action("ListadoNoticias", "Noticias")

	</div>

</body>

<!-- Llamada a los scripts de la página- -->
<script type="text/javascript" charset="UTF-8">
    require(['app/login/login', 'domReady!'], function (loginController)
    {
        var login = new loginController();
        login.Init();
    });
</script>

</html>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/LogOn/InfoUsuario.cshtml
@model SolicitudIntegralMVC.Models.UserLogon
@if(Model != null)
{
<div>
    <label>[@Model.NombreUsuario]</label>
    <label>@Model.NombreCompletoUsuario</label>
    |
    <label>Nodo: @Model.NodoAtencionActual</label>
    |
    <label>[@Model.SubdivisionActual]</label>
    <label>@Model.DescripcionSubdivisionActual</label>
    >>
    <label>@Model.SiglasActivoActual</label>
    >>
    <label>@Model.SiglasRegionActual</label>
</div>
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/LogOn/RelacionarCuentaUsuarioDominio.cshtml
@model SolicitudIntegralMVC.Models.UserLogon

<div id="crelacion-cuenta-usuario-dominio" class="grid">

    <div class="row">

        <div class="span2">
            <label>Cuenta de Dominio:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="txtCuentaDominio" value="@Request.LogonUserIdentity.Name"/>
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Usuario sistema</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="txtUsuarioSistema" value=""/>
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Contraseña:</label>
        </div>

        <div class="span3 input-control text">
            <input type="password" id="txContraseña" value=""/>
        </div>

    </div>

     <div style="float:right; margin-top:15px;">
        <input type="button" id="btnAceptar" value="Guardar" />
        <input type="button" id="btnCerrar" value="Cerrar" />
    </div>

</div>