SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/CatalogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SolicitudIntegralMVC.Infraestructure;
using SolicitudIntegralMVC.Infraestructure.Concrete;
using STPIntegral.Negocios;

namespace SolicitudIntegralMVC.Controllers
{
    [Authorize]
    [AjaxAuthorizationAttribute]
    [CustomAuthSessionRoleAttribute("VENTANILLA", "USUARIO")]
    public class CatalogosController : Controller
    {
        //
        // GET: /Catalogos/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult BusquedaCompanias()
        {
            return PartialView();
        }


        [HttpGet]
        public ActionResult EmpleadosCompania()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult EmpleadosPemex()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ConsultaCompanias(string buscar, string buscarPor)
        {
            ActionResult resultado = null;

            try
            {
                List<GestionGL.Datos.C_ACREEDORES> listado_companias = null;

                using (GestionGL.Datos.GestionGLModel gestionGlModel = new GestionGL.Datos.GestionGLModel())
                {
                    switch (buscarPor)
                    {
                        case "NombreCompania":
                            listado_companias = gestionGlModel.C_ACREEDORES.Where(x => x.DESCRIPCION_ACREEDOR.Contains(buscar)).Take(100).ToList();
                            break;
                        case "Rfc":
                            listado_companias = gestionGlModel.C_ACREEDORES.Where(x => x.RFC_ACREEDOR.Contains(buscar)).Take(100).ToList();
                            break;
                        case "NoAcreedor":
                            listado_companias = gestionGlModel.C_ACREEDORES.Where(x => x.CVE_ACREEDOR.Contains(buscar)).Take(100).ToList();
                            break;
                    }

                    
                }
                
                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = listado_companias }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }

            return resultado;
        }

        [HttpPost]
        public ActionResult GuardarEmpleadoCompania(GestionGL.Datos.C_EMPLEADOS_CIA empleadoCia)
        {
            ActionResult resultado = null;

            try
            {
                empleadoCia = STPIntegral.Negocios.CEmpleadoCia.GuardarEmpleado(empleadoCia);

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = empleadoCia, mensaje = String.Format("Se han guardado los datos del empleado: [{0}] {1} {2}",empleadoCia.RFC_FM3, empleadoCia.NOMBRES, empleadoCia.APELLIDOS) }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }

            return resultado;
        }

        [HttpPost]
        public ActionResult GuardarEmpleadoPemex(GestionGL.Datos.C_EMPLEADOS_PEMEX empleadoPemex)
        {
            ActionResult resultado = null;

            try
            {
                empleadoPemex = STPIntegral.Negocios.CEmpleadoPemex.GuardarEmpleado(empleadoPemex);

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = empleadoPemex, mensaje = String.Format("Se han guardado los datos del empleado: [{0}] {1} {2}", empleadoPemex.FICHA, empleadoPemex.NOMBRES, empleadoPemex.APELLIDOS) }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }


            return resultado;
        }
    }
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Catalogos/BusquedaCompanias.cshtml
    <div id="frmBusquedaCompanias">
        <div class="grid">

            <div class="row">
                <input type="text" class="span4" id="txtBuscar" placeholder="Frase de Busqueda..." />
                 <button class="btn" type="button" data-bind="click: BusquedaCompanias" ><img src="~/Content/images/defaulticon/16x16/search.png"/></button>
            </div>
            <div class="row">
                <select class="span2" id="sltBuscarPor">
                    <option value="NombreCompania">Nombre de la Compañia</option>
                    <option value="Rfc" selected>RFC Compañia</option>
                    <option value="NoAcreedor">No. Acreedor SAP</option>
                </select>
            </div>

            <div class="row">
                <h2>Resultados de la busqueda</h2>    
            </div>

            <div class="row">
            <div class="">
                <div class="scrollingArea">
                    <table class="scrolling">
                        <thead>
                            <tr>
                                <th class="Nombre">Nombre</th>
                                <th class="Rfc">RFC</th>
                                <th class="NoSap">No.Sap</th>
                                <th class="Seleccionar">Seleccionar</th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach: listado_companias_busqueda">
                            <tr>
                                <td class="Nombre" data-bind="text: $data.DESCRIPCION_ACREEDOR" ></td>
                                <td class="Rfc" data-bind="text: $data.RFC_ACREEDOR" ></td>
                                <td class="NoSap" data-bind="text: $data.CVE_ACREEDOR" ></td>
                                <!--<td><button data-bind="click: $root.SeleccionaCompania"><img src="~/Content/images/defaulticon/16x16/check.png"/></button> </td>-->
                                <td class="Seleccionar"><a href="#" data-bind="click: $root.SeleccionaCompania"><img src="~/Content/images/glyphicons/glyphicons_198_ok.png"/></a> </td>
                                <!--<td><button class="mini" data-bind="click: $root.SeleccionaCompania"><img src="~/Content/images/glyphicons/glyphicons_198_ok.png"/></button> </td>-->
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
                <br />
                <input id="btnCerrar" type="button" value="Cerrar" />
            </div>
        </div>

    </div>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Catalogos/EmpleadosCompania.cshtml
<div id="calalogo-empleados-cia" class="grid">
    
    <h3>Catalogo de Empleados de Compañia</h3>

    
    @using (Html.BeginForm("GuardarEmpleadoCompania", "Catalogos", FormMethod.Post, new { id = "frmCatalogoEmpleadoCia" }))
    { 

    <div class="row">

        <div class="span2">
            <label>RFC:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="RFC_FM3" data-bind="value: EmpleadoCia().RFC_FM3, enable: EmpleadoCia().ID_C_EMPLEADO_CIA() <= 0"/>
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Nombres:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="NOMBRES" data-bind="value: EmpleadoCia().NOMBRES, enable: EmpleadoCia().ID_C_EMPLEADO_CIA() <= 0" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Apellidos:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="APELLIDOS" data-bind="value: EmpleadoCia().APELLIDOS, enable: EmpleadoCia().ID_C_EMPLEADO_CIA() <= 0" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Categoria:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="CATEGORIA" data-bind="value: EmpleadoCia().CATEGORIA" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Genero:</label>
        </div>

        <div class="span3 input-control text">
            <select id="GENERO" data-bind="value: EmpleadoCia().GENERO">
                <option value="HOMBRE">HOMBRE</option>
                <option value="MUJER">MUJER</option>
            </select>
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Nacionalidad:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="NACIONALIDAD" data-bind="value: EmpleadoCia().NACIONALIDAD" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Folio libreta Mar:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="FOLIO_LIBRETA_MAR" data-bind="value: EmpleadoCia().FOLIO_LIBRETA_MAR" />
        </div>

    </div>

    <div class="row" data-bind="visible: Date.parse(EmpleadoCia().VIGENCIA_LIBRETA_MAR()) < (new Date())">
        <label class="border-color-red fg-color-red" >La vigencia de la libreta de mar esta vencida, favor de actualizar.</label>
    </div>
        
    <div class="row">

        <div class="span2">
            <label>Vigencia Libreta:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="VIGENCIA_LIBRETA_MAR" data-bind="value: EmpleadoCia().VIGENCIA_LIBRETA_MAR" />
        </div>

    </div>
        
    <div style="float:right; margin-top:15px;">
        <input type="submit" id="btnAceptar" value="Guardar" />
        <input type="button" id="btnCerrar" value="Cerrar" />
    </div>
        
    }

    
</div>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Catalogos/EmpleadosPemex.cshtml
<div id="calalogo-empleados-pemex" class="grid">
    
    <h3>Catalogo de Empleados de Pemex</h3>

    @using (Html.BeginForm("GuardarEmpleadoPemex", "Catalogos", FormMethod.Post, new { id = "frmCatalogoEmpleadoPemex" }))
    { 

    <div class="row">

        <div class="span2">
            <label>Ficha:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="FICHA" data-bind="value: EmpleadoPemex().FICHA, enable: EmpleadoPemex().ID_C_EMPLEADO_PEMEX() <= 0"/>
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Nombres:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="NOMBRES" data-bind="value: EmpleadoPemex().NOMBRES, enable: EmpleadoPemex().ID_C_EMPLEADO_PEMEX() <= 0" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Apellidos:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="APELLIDOS" data-bind="value: EmpleadoPemex().APELLIDOS, enable: EmpleadoPemex().ID_C_EMPLEADO_PEMEX() <= 0" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>Categoria:</label>
        </div>

        <div class="span3 input-control text">
            <input type="text" id="CATEGORIA" data-bind="value: EmpleadoPemex().CATEGORIA" />
        </div>

    </div>

    <div class="row">

        <div class="span2">
            <label>GENERO:</label>
        </div>

        <div class="span3 input-control text">
            <select id="GENERO" data-bind="value: EmpleadoPemex().GENERO">
                <option value="HOMBRE">HOMBRE</option>
                <option value="MUJER">MUJER</option>
            </select>
        </div>

    </div>
        
    <div style="float:right; margin-top:15px;">
        <input type="submit" id="btnAceptar" value="Guardar" />
        <input type="button" id="btnCerrar" value="Cerrar" />
    </div>
    }
    
</div>