SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/FoliosVisitaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using STPIntegral.Negocios;

namespace SolicitudIntegralMVC.Controllers
{
    public class FoliosVisitaController : Controller
    {
        //
        // GET: /FoliosVisita/

        [HttpGet]
        public ActionResult Index()
        {
            STPIntegral.Datos.TabFolioVisitas folio_nuevo = null;
            folio_nuevo = new STPIntegral.Datos.TabFolioVisitas();
            folio_nuevo.FechaInicio = DateTime.MinValue;
            folio_nuevo.FechaFin = DateTime.MinValue;
            return View(folio_nuevo);
        }

        [HttpPost]
        public ActionResult Index(string FolioVisitaData)
        {
            string[] folioVisita = FolioVisitaData.Split('|');
            int IdFolioVisitaConvertido=0;
            DateTime FechaInicioConvertido = DateTime.MinValue;
            DateTime FechaFinConvertido = DateTime.MinValue;
            Int32.TryParse(folioVisita[0], out IdFolioVisitaConvertido);
            DateTime.TryParse(folioVisita[3], out FechaInicioConvertido);
            DateTime.TryParse(folioVisita[4], out FechaFinConvertido);

            STPIntegral.Datos.TabFolioVisitas folioVisitaEditar = null;
            folioVisitaEditar = new STPIntegral.Datos.TabFolioVisitas();
            
            folioVisitaEditar.IdFolioVisita = IdFolioVisitaConvertido;
            folioVisitaEditar.Foliodocumento = folioVisita[1] == null ? "" : folioVisita[1];
            folioVisitaEditar.FolioVisita = folioVisita[2] == null ? "" : folioVisita[2];
            folioVisitaEditar.FechaInicio = FechaInicioConvertido;
            folioVisitaEditar.FechaFin = FechaFinConvertido;
            folioVisitaEditar.RfcCompania = folioVisita[5] == null ? "" : folioVisita[5];
            folioVisitaEditar.NoAcreedorSap = folioVisita[6] == null ? "" : folioVisita[6];
            folioVisitaEditar.NombreCompania = folioVisita[7] == null ? "" : folioVisita[7];
            folioVisitaEditar.FichaSolicitante = folioVisita[8] == null ? "" : folioVisita[8];
            folioVisitaEditar.FichaAutorizador = folioVisita[9] == null ? "" : folioVisita[9];
            folioVisitaEditar.Motivo = folioVisita[10] == null ? "" : folioVisita[10];

            return View(folioVisitaEditar);
        }

        [HttpPost]
        public ActionResult GuardarFolioVisita(STPIntegral.Datos.TabFolioVisitas folioVisita)
        {
            //folioVisita.EstadoFolioVisita = "0000012215421564654";
            //folioVisita.FichaAutorizador = "02145123456";

            //return View("Index", folioVisita);

            SolicitudIntegralMVC.Models.UserLogon usuario_logueado = SolicitudIntegralMVC.Infraestructure.Utilerias.ObtenerUsuarioAutentificado(this.HttpContext);
            ActionResult resultado = null;
            folioVisita.NodoTransporte = usuario_logueado.NodoAtencionActual;
            folioVisita.FichaCaptura = usuario_logueado.NombreUsuario;
            folioVisita.FechaCaptura = DateTime.Now;
            folioVisita.EstadoFolioVisita = "Activo";
            try
            {
                folioVisita = STPIntegral.Negocios.FoliosVisita.GuardarFolio(folioVisita);

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = folioVisita, mensaje = String.Format("Se ha guardado el siguiente folio de visita: [{0}]", folioVisita.FolioVisita) }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }


            return resultado;
        }


        [HttpGet]
        public ActionResult Listado()
        {

            List<STPIntegral.Datos.TabFolioVisitas> folios_visita = null;

            return View(folios_visita);
        }

        [HttpGet]
        public ActionResult BusquedaFoliosVisita(string fraseBusqueda)
        {
            ActionResult resultado = null;

            try
            {
                List<STPIntegral.Datos.TabFolioVisitas> folios_visita = null;

                using (STPIntegral.Datos.STPIntegralModel stpIntegralModel = new STPIntegral.Datos.STPIntegralModel())
                {
                    folios_visita = stpIntegralModel.TabFolioVisitas.Where(x => x.BorradoLogico == false && x.FolioVisita.Contains(fraseBusqueda)).ToList();
                }

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = folios_visita }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }

            return resultado;
        }
        
        [HttpGet]
        public ActionResult ConsultaAutorizador(string ficha_autorizador)
        {
            ActionResult resultado = null;

            try
            {
                GestionGL.Datos.C_EMPLEADOS_PEMEX empleado = null;

                using (GestionGL.Datos.GestionGLModel gestionGlModel = new GestionGL.Datos.GestionGLModel())
                {
                    empleado = gestionGlModel.C_EMPLEADOS_PEMEX.Where(x => x.FICHA==ficha_autorizador).FirstOrDefault();
                }

                if (empleado == null)
                {
                    throw new System.Exception("No se encontro ningun autorizador con esa ficha");
                }

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = empleado }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }



            return resultado;
        }

        public ActionResult ConsultaSolicitante(string ficha_solicitante)
        {
            ActionResult resultado = null;

            try
            {
                GestionGL.Datos.C_EMPLEADOS_PEMEX empleado = null;

                using (GestionGL.Datos.GestionGLModel gestionGlModel = new GestionGL.Datos.GestionGLModel())
                {
                    empleado = gestionGlModel.C_EMPLEADOS_PEMEX.Where(x => x.FICHA==ficha_solicitante).FirstOrDefault();
                }

                if (empleado == null)
                {
                    throw new System.Exception("No se encontro ningun solicitante con esa ficha");
                }

                if (Request.IsAjaxRequest())
                {
                    resultado = Json(new { result = empleado }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (ShowCaseException ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "ApplicationException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.AddHeader("RESPONSE_STATUS", "UnexpectedException");
                TempData["Error"] = ex;
                resultado = Request.IsAjaxRequest() ? (ActionResult)Content(ShowCaseException.SerializeException(ex)) : (ActionResult)RedirectToAction("Index");
            }



            return resultado;
        }
    }
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/FoliosVisita/Index.cshtml
@model  STPIntegral.Datos.TabFolioVisitas

@{
    ViewBag.Title = "Solicitud Integral: Folios de Visita";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="offset1">
    <h2>Folios de Visita</h2>

</div>
<div class="grid" id="folios-visita">

    @using (Html.BeginForm("GuardarFolioVista", "FoliosVisita", FormMethod.Post, new { id = "frmFolioVisita" }))
    {
        <br />
        <div class="offset1">

        <div class="row">
        <button id="btnBuscar" hidden="hidden" disabled="disabled" class="image-button" name="btnBuscar" type="button" >Buscar<img src="~/Content/images/glyphicons/glyphicons_027_search.png"/></button>
        <button id="btnAniadir" class="image-button" name="btnAniadir" type="button" data-bind="click: AniadirFolio" >Añadir<img src="~/Content/images/glyphicons/glyphicons_298_hospital.png"/></button>
        <button id="btnEditar" hidden="hidden" disabled="disabled" class="image-button"  name="btnEditar" type="button" data-bind="click: EditarFolio" >Editar<img src="~/Content/images/glyphicons/glyphicons_151_edit.png"/></button>
        <button id="btnCancelar" hidden="hidden" disabled="disabled" class="image-button" name="btnCancelar" type="button" data-bind="click: CancelarFolio" >Cancelar<img src="~/Content/images/glyphicons/glyphicons_221_unshare.png"/></button>
        <button id="btnEliminar" hidden="hidden" disabled="disabled" class="image-button" name="btnEliminar" type="button" data-bind="click: EliminarFolio" >Eliminar<img src="~/Content/images/glyphicons/glyphicons_192_circle_remove.png"/></button>
        <button id="btnGuardar" hidden="hidden" disabled="disabled" class="image-button" name="btnGuardar" type="button" data-bind="click: GuardarFolio" >Guardar<img src="~/Content/images/glyphicons/glyphicons_193_circle_ok.png"/></button>
        <button id="btnLista" class="image-button" name="btnLista" type="button" onclick="window.open('/FoliosVisita/Listado');">Ver lista<img src="~/Content/images/glyphicons/glyphicons_193_circle_ok.png"/></button>
        </div>
        <br />

        <div class="row" hidden="hidden">
            <input type="text" id="txtIdFolioVisita" hidden="hidden" disabled="disabled" name="IdFolioVisita" value="@Model.IdFolioVisita" />
        </div>

        <div class="row">
            <label class="span2">Folio Documento</label>
            <input id="txtFolioDocumento" disabled="disabled" class="span4" type="text" name="FolioDocumento" value="@Model.Foliodocumento" data-bind="value: FolioDocumento" />
        </div>

        <div class="row">
            <label class="span2">Folio Visita</label>
            <input id="txtFolioVisita" disabled="disabled" class="span4" type="text" name="FolioVisita" value="@Model.FolioVisita" data-bind="value: FolioVisita" />
        </div>   
        
        <div class="row">
            <label class="span2">Fecha Inicio</label>
            <input id="txtFechaInicio" disabled="disabled" class="span4" type="text" name="FechaInicio" value="@if(Model.FechaFin!=DateTime.MinValue){@Model.FechaInicio.ToString("dd/MM/yyyy")}" data-bind="value: FechaInicio" />
        </div>

        <div class="row">
            <label class="span2">Fecha Fin</label>
                <input id="txtFechaFin" disabled="disabled" class="span4" type="text" name="FechaFin" value="@if(Model.FechaFin!=DateTime.MinValue){@Model.FechaFin.ToString("dd/MM/yyyy")}" data-bind="value: FechaFin" />
        </div>    

        <!--<div class="row">
            <label class="span2">Busqueda Compañias</label>
            <input id="txtBusqueda" disabled="disabled" class="span4" type="text" name="Bus" value="" />
        </div>-->
<div class="row">
        <div class="row">
            <label class="span2">RFC Compañia</label>
            <input id="txtRFCCompania" disabled="disabled" class="span4" type="text" name="RFCCompania" value="@Model.RfcCompania" data-bind="value: RfcCompania" />
            <button disabled="disabled" class="btn" type="button" id="btnBusquedaCompania" name="btnBusquedaCompania" data-bind="click: MostrarBusquedaCompanias"><img src="~/Content/images/defaulticon/16x16/open-in-new-window.png"/></button>
        </div>
        <div class="row">
            <label class="span2">No. Acreedor SAP</label>
            <input id="txtNoAcreedorSAP" disabled="disabled" class="span4" type="text" name="NoAcreedorSAP" value="@Model.NoAcreedorSap" data-bind="value: NoAcreedorSap" />
        </div>
        <div class="row">
            <label class="span2">Compañia</label>
            <input id="txtCompania" disabled="disabled" class="span4" type="text" name="Compania" value="@Model.NombreCompania" data-bind="value: NombreCompania" />
        </div>
    </div>

        <div class="row">
            <label class="span2">Ficha del Solitante</label>
            <input id="txtFichaSolicitante" disabled="disabled" class="span4" type="text" name="FichaSolicitante" value="@Model.FichaSolicitante" data-bind="value: FichaSolicitante" />
            <button id="btnValidarSolicitante" disabled="disabled" class="btn" name="btnValidarSolicitante" type="button" data-bind="click: ValidarSolicitante"><img src="~/Content/images/defaulticon/16x16/search.png"/></button>
            <span id="image-loading-solicitante" class="loading-image" style="display: none;">
                <img src="/Content/images/icons/loading.gif">
            </span>
            <label data-bind="text: NombreSolicitante"></label>
        </div>
    
        <div class="row">
            <label class="span2">Ficha del Autorizador</label>
            <input id="txtFichaAutorizador" disabled="disabled" class="span4" type="text" name="FichaAutorizador" value="@Model.FichaAutorizador" data-bind="value: FichaAutorizador" />
            <button id="btnValidarAutorizador" disabled="disabled" class="btn" name="btnValidarAutorizador" type="button" data-bind="click: ValidarAutorizador"><img src="~/Content/images/defaulticon/16x16/search.png"/></button>
            <span id="image-loading-autorizador" class="loading-image" style="display: none;">
                <img src="/Content/images/icons/loading.gif">
            </span>
            <label data-bind="text: NombreAutorizador"></label>
        </div>
        
        <!--<div class="row" hidden="hidden">
            <input id="chkFolioActivo" disabled="disabled" hidden="hidden" type="checkbox" name="chkFolioActivo" value="" data-bind="checked: BorradoLogico"/>
        </div>-->
        
        <div class="row">
            <label class="span2">Observaciones</label>
            <textarea id="txtMotivo" disabled="disabled" class="span4" name="Motivo" placeholder="Introduzca sus comentarios aqui..." data-bind="value: Motivo">@Model.Motivo</textarea>
        </div>
        </div>    
    }
</div>
 <!-- Html.ActionLink("Ir al listado de Folios de Visita", "Listado", "FoliosVisita")-->

 <!-- Llamada a los scripts de la página- -->
<script type="text/javascript" charset="UTF-8" >
    require(['app/FoliosVisita/CatalogoFoliosVisita', 'domReady!'], function (CatalogosFoliosVisita)
    {
        var folios_visita = new CatalogosFoliosVisita();
        folios_visita.Init();
    });
</script>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/FoliosVisita/Listado.cshtml
@{
    ViewBag.Title = "Listado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    
<h2>Listado Folios Visita</h2>
    <div id="frmListadoFolioVisita">
        <div class="grid">
            
            <div class="row">   
                 <div class="span4">
                    <input type="text" class="span3" id="txtBuscar" placeholder="Buscar Folio de Visita..." />
                    <button class="btn" type="button" data-bind="click: BusquedaFoliosVisita" ><img src="~/Content/images/defaulticon/16x16/search.png"/></button>
                 </div>
                 <div class="span3">@Html.ActionLink("Nuevo Folio Visita", "Index", "FoliosVisita")</div>
            </div>
            <div class="row">
                <table class="bordered striped">
                    <thead>
                    <tr>
                        <td hidden="hidden">Id Folio</td>
                        <td>Folio Documento</td>
                        <td>Folio Visita</td>
                        <td>Fecha Inicio</td>
                        <td>Fecha Fin</td>
                        <td>RFC</td>
                        <td>No. Acreedor SAP</td>
                        <td>Compañia</td>
                        <td>Ficha Solicitante</td>
                        <td>Ficha Autorizador</td>
                        <td>Observaciones</td>
                        <td>Editar</td>
                    </tr>
                    </thead>
                    <tbody data-bind="foreach: listado_folios">
                        <tr>
                            <td data-bind="text: $data.IdFolioVisita" hidden="hidden"></td>
                            <td data-bind="text: $data.Foliodocumento"></td>
                            <td data-bind="text: $data.FolioVisita"></td>
                            <td data-bind="text: parseDate($data.FechaInicio)"></td>
                            <td data-bind="text: parseDate($data.FechaFin)"></td>
                            <td data-bind="text: $data.RfcCompania"></td>
                            <td data-bind="text: $data.NoAcreedorSap"></td>
                            <td data-bind="text: $data.NombreCompania"></td>
                            <td data-bind="text: $data.FichaSolicitante"></td>
                            <td data-bind="text: $data.FichaAutorizador"></td>
                            <td data-bind="text: $data.Motivo"></td>
                            <td><a id="HoverSinColor" href="#" data-bind="click: $root.EditarFolio"><img src="~/Content/images/glyphicons/glyphicons_151_edit.png"/></a></td>
                        </tr>
                    </tbody>

                </table>
            </div>
        </div>
    </div>

<script type="text/javascript" charset="UTF-8" >
    require(['app/FoliosVisita/CatalogoFoliosVisitaLista', 'domReady!'], function (CatalogosFoliosVisita)
    {
        var folios_visita = new CatalogosFoliosVisita();
        folios_visita.Init();
    });
</script>