SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/FirmaElectronicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SolicitudIntegralMVC.Controllers
{
    public class FirmaElectronicaController : Controller
    {
        //
        // GET: /FirmaElectronica/

        [HttpGet]
        public ActionResult Index(string FolioSolicitud)
        {
            STPIntegral.Datos.TabSolicitudIntegral solicitud_integral = null;

            if (FolioSolicitud != null)
            {
                using (STPIntegral.Datos.STPIntegralModel stpIntegralModel = new STPIntegral.Datos.STPIntegralModel())
                {
                    solicitud_integral = stpIntegralModel.TabSolicitudIntegral.FirstOrDefault(x => x.FolioSolicitudIntegral == FolioSolicitud);
                }
            }


            return View(solicitud_integral);
        }

        [HttpPost]
        public ActionResult CrearFichaCustodia()
        {
            ActionResult resultado = null;

            SUFE.Contenidos.ContenidosSoapClient contenidos = new SUFE.Contenidos.ContenidosSoapClient();
            SUFE.Contenidos.CredencialesHeader credenciales_header = new SUFE.Contenidos.CredencialesHeader();
            SUFE.Contenidos.Contenidos contenido = new SUFE.Contenidos.Contenidos();

            //contenido.Sha256B64;

            contenidos.Agregar(new SUFE.Contenidos.CredencialesHeader() { }, new SUFE.Contenidos.Contenidos() { });

            int i = 0;

            return resultado;
        }

        [HttpGet]
        public ActionResult ObtenerHash()
        {
            ActionResult resultado = null;

            SUFE.Contenidos.ContenidosSoapClient contenidos = new SUFE.Contenidos.ContenidosSoapClient();
            
            SUFE.Contenidos.LlavePrimaria llave_primaria = new SUFE.Contenidos.LlavePrimaria();
            SUFE.Contenidos.CredencialesHeader credenciales = new SUFE.Contenidos.CredencialesHeader();

            credenciales.AppKey = "Test";

            llave_primaria.SistemaOrigen = "Test";
            llave_primaria.TipoDocumento = "Solicitud Integral";
            llave_primaria.FDocumento = String.Format("{0:yyyy-MM-dd}",System.DateTime.Now);
            llave_primaria.IDDocumento = "SI-10062013-0004";

            SUFE.Contenidos.Contenidos[] contenidos_respuesta = null;
            contenidos_respuesta = contenidos.ObtenerHash(credenciales, llave_primaria);

            return resultado;
        }

    }
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/LogOnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SolicitudIntegralMVC.Infraestructure;
using SolicitudIntegralMVC.Infraestructure.Abstract;
using STPIntegral.Negocios;

namespace SolicitudIntegralMVC.Controllers
{
    [AllowAnonymous]
    public class LogOnController : Controller
    {
        //
        // GET: /LogOn/

        public LogOnController()
        {
        }

        public ActionResult Index()
        {
            SolicitudIntegralMVC.Models.UserLogonModel loginModel = new Models.UserLogonModel();

            loginModel.UsuarioDominio = ObtenerUsuarioDominio();

            Session["pre_login_user"] = loginModel;

            return View(loginModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult ValidarUsuarioPassword(SolicitudIntegralMVC.Models.UserLogonModel user_login)
        {
            if (STPIntegral.Negocios.Utilerias.ObtenerTipoTrabajador(user_login.UsuarioFormulario.NombreUsuario) == "PEMEX")
            {
                user_login.UsuarioFormulario.NombreUsuario = STPIntegral.Negocios.Utilerias.FormatearFichaRfc(user_login.UsuarioFormulario.NombreUsuario);
            }

            user_login.UsuarioDominio = ObtenerUsuarioDominio();
            user_login.UsuarioFormulario = ValidarUsuarioPassword(user_login.UsuarioFormulario.NombreUsuario, user_login.UsuarioFormulario.Password);

            if (user_login.UsuarioFormulario != null && user_login.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles != null && user_login.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Count <= 0)
            {
                TempData["mensaje_error"] = "Usuario o Contraseña incorrectos";
            }
            else
            {
                Session["pre_login_user"] = user_login;
            }


            return View("index",user_login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogInUsuarioFormulario(SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso)
        {
            ActionResult resultado = null;

            if (Session["pre_login_user"] != null)
            {
                SolicitudIntegralMVC.Models.UserLogonModel pre_login_user = Session["pre_login_user"] as SolicitudIntegralMVC.Models.UserLogonModel;

                if (pre_login_user != null && pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles != null && pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Any(x => x.IdPermisoUa == permiso.IdPermisoUa))
                {
                    FormsAuthentication.SetAuthCookie(pre_login_user.UsuarioFormulario.NombreUsuario, false);

                    SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso_actual = pre_login_user.UsuarioFormulario.ListadoPermisosSubdivisionesDisponibles.Single(x => x.IdPermisoUa == permiso.IdPermisoUa);

                    pre_login_user.UsuarioFormulario.NodoAtencionActual = String.IsNullOrEmpty(permiso_actual.NodoAtencion) || (!String.IsNullOrEmpty(permiso_actual.NodoAtencion) && permiso_actual.NodoAtencion.Trim() == "") ? "CME" : permiso_actual.NodoAtencion;
                    
                    pre_login_user.UsuarioFormulario.IdPermisoUaActual = permiso_actual.IdPermisoUa;
                    pre_login_user.UsuarioFormulario.IdDUsuarioActual = permiso_actual.IdDUsuario;
                    pre_login_user.UsuarioFormulario.IdMUsuarioActual = permiso_actual.IdMUsuario;

                    pre_login_user.UsuarioFormulario.PermisoUsuarioActual = permiso_actual.Permiso.Trim('[', ']');

                    pre_login_user.UsuarioFormulario.CveActivoActual = permiso_actual.CveActivo;
                    pre_login_user.UsuarioFormulario.CveRegionActual = permiso_actual.CveRegion;
                    pre_login_user.UsuarioFormulario.DescripcionActivoActual = permiso_actual.DescripcionActivo;
                    pre_login_user.UsuarioFormulario.DescripcionRegionActual = permiso_actual.DescripcionRegion;
                    pre_login_user.UsuarioFormulario.SubdivisionActual = permiso_actual.Subdivision;
                    pre_login_user.UsuarioFormulario.DescripcionSubdivisionActual = permiso_actual.DescripcionSubdivision;

                    if (String.IsNullOrEmpty(pre_login_user.UsuarioFormulario.NodoAtencionActual))
                    {
                        pre_login_user.UsuarioFormulario.NodoAtencionActual = "CME";
                    }

                    SolicitudIntegralMVC.Infraestructure.Utilerias.GuardarUsuarioAutentificado(this.HttpContext, pre_login_user.UsuarioFormulario);

                    SolicitudIntegralMVC.Infraestructure.Concrete.FormsAuthProvider authProvider = new Infraestructure.Concrete.FormsAuthProvider();
                    authProvider.Authenticate(pre_login_user.UsuarioFormulario.NombreUsuario, pre_login_user.UsuarioFormulario.Password);
                    
                    resultado = RedirectToAction("Index","Home");
                }
            }
            else
            {
                TempData["mensaje_error"] = "Ocurrio un error con el intento de acceder, por favor intentelo de nuevo";
                resultado = View("index");
            }

            return resultado;
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogInUsuarioDominio(SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso)
        {
            ActionResult resultado = null;

            if (Session["pre_login_user"] != null)
            {
                SolicitudIntegralMVC.Models.UserLogonModel pre_login_user = Session["pre_login_user"] as SolicitudIntegralMVC.Models.UserLogonModel;
                 
                if (pre_login_user != null && pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles != null && pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles.Any(x => x.IdPermisoUa == permiso.IdPermisoUa))
                {
                    FormsAuthentication.SetAuthCookie(pre_login_user.UsuarioDominio.NombreUsuario, false);

                    SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso_actual = pre_login_user.UsuarioDominio.ListadoPermisosSubdivisionesDisponibles.First(x => x.IdPermisoUa == permiso.IdPermisoUa);

                    pre_login_user.UsuarioFormulario.NodoAtencionActual = String.IsNullOrEmpty(permiso_actual.NodoAtencion) || (!String.IsNullOrEmpty(permiso_actual.NodoAtencion) && permiso_actual.NodoAtencion.Trim() == "") ? "CME" : permiso_actual.NodoAtencion;

                    pre_login_user.UsuarioDominio.IdPermisoUaActual = permiso_actual.IdPermisoUa;
                    pre_login_user.UsuarioFormulario.IdDUsuarioActual = permiso_actual.IdDUsuario;
                    pre_login_user.UsuarioFormulario.IdMUsuarioActual = permiso_actual.IdMUsuario;

                    pre_login_user.UsuarioDominio.PermisoUsuarioActual = permiso_actual.Permiso.Trim('[', ']');

                    pre_login_user.UsuarioDominio.CveActivoActual = permiso_actual.CveActivo;
                    pre_login_user.UsuarioDominio.CveRegionActual = permiso_actual.CveRegion;
                    pre_login_user.UsuarioDominio.DescripcionActivoActual = permiso_actual.DescripcionActivo;
                    pre_login_user.UsuarioDominio.DescripcionRegionActual = permiso_actual.DescripcionRegion;
                    pre_login_user.UsuarioDominio.SubdivisionActual = permiso_actual.Subdivision;
                    pre_login_user.UsuarioDominio.DescripcionSubdivisionActual = permiso_actual.DescripcionSubdivision;
                    pre_login_user.UsuarioDominio.SiglasActivoActual = permiso_actual.SiglasActivo;
                    pre_login_user.UsuarioDominio.SiglasRegionActual = permiso_actual.SiglasRegion;

                    if (String.IsNullOrEmpty(pre_login_user.UsuarioFormulario.NodoAtencionActual))
                    {
                        pre_login_user.UsuarioFormulario.NodoAtencionActual = "CME";
                    }

                    SolicitudIntegralMVC.Infraestructure.Utilerias.GuardarUsuarioAutentificado(this.HttpContext, pre_login_user.UsuarioDominio);

                    SolicitudIntegralMVC.Infraestructure.Concrete.FormsAuthProvider authProvider = new Infraestructure.Concrete.FormsAuthProvider();

                    authProvider.Authenticate(pre_login_user.UsuarioDominio.NombreUsuario, pre_login_user.UsuarioDominio.Password);

                    resultado = RedirectToAction("Index", "Home");
                }
            }
            else
            {
                TempData["mensaje_error"] = "Ocurrio un error con el intento de acceder, por favor intentelo de nuevo";
                resultado = View("index");
            }

            return resultado;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult RelacionarCuentaUsuarioDominio()
        {
            return PartialView();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RelacionarCuentaUsuarioDominio(string dominio, string usuario, string password)
        {
            ActionResult resultado = null;

            try
            {
                SolicitudIntegralMVC.Models.UserLogon permiso = ValidarUsuarioPassword(usuario, password);

                if (permiso != null)
                {
                    STPIntegral.Negocios.UsuariosController.ActualizarNombreUsuarioDominio(permiso.IdMUsuarioActual, password, dominio);
                }
                else
                {
                    throw new ShowCaseException("Usuario o contraseña invalidos", null, TypeMessage.warning, "");
                }

                resultado = Json(new { result = "OK", mensaje = "La cuenta del dominio se asigno exitosamente." }, JsonRequestBehavior.AllowGet);
            }

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SolicitudIntegralMVC.Infraestructure;
using SolicitudIntegralMVC.Infraestructure.Concrete;
using STPIntegral.Negocios;

namespace SolicitudIntegralMVC.Controllers
{

    [Authorize]
    [AjaxAuthorizationAttribute]
    [CustomAuthSessionRoleAttribute("VENTANILLA", "USUARIO")]
    public class UsuariosController : Controller
    {
        //
        // GET: /Usuarios/

        [HttpGet]
        public ActionResult Index()
        {
            Models.CatalogoUsuarioViewModel usuarioViewModel = ObtenerUsuarioViewModel();

            return View(usuarioViewModel);
        }

        private Models.CatalogoUsuarioViewModel ObtenerUsuarioViewModel()
        {
            SolicitudIntegralMVC.Models.UserLogon usuario_logueado = SolicitudIntegralMVC.Infraestructure.Utilerias.ObtenerUsuarioAutentificado(this.HttpContext);
            GestionGL.Datos.M_USUARIOS usuario = STPIntegral.Negocios.UsuariosController.ObtenerMUsuario(usuario_logueado.IdMUsuarioActual);
            Models.CatalogoUsuarioViewModel usuarioViewModel = new Models.CatalogoUsuarioViewModel()
            {
                IdUsuario = usuario.ID_M_USUARIO,
                NombreCompleto = usuario.NOMBRE,
                NombreUsuario = usuario.FICHA,
                NuevaContrasenia = "",
                UsuarioDominio = usuario.DOMINIO
            };

            return usuarioViewModel;
        }

        [HttpPost]
        public ActionResult CambiarContrasenia(Models.CatalogoUsuarioViewModel usuario)
        {
            string mensaje = "";

            try
            {
                if (String.IsNullOrEmpty(usuario.ContaseniaAnteriorCambioContrasenia))
                {
                    usuario.ContaseniaAnteriorCambioDominio = "";
                }

                STPIntegral.Negocios.UsuariosController.CambiarContrasenia(usuario.IdUsuario, usuario.ContaseniaAnteriorCambioContrasenia, usuario.NuevaContrasenia);
                mensaje = "Se ha modificado correctamente la contraseña del usuario";
            }
            catch (ShowCaseException ex)
            {
                mensaje = String.Format("Ocurrio el siguiente error al actualizar: {0}", ex.Message);
            }
            catch (System.Exception ex)
            {
                mensaje = String.Format("Ocurrio el siguiente error al actualizar: {0}", ex.Message);
            }

            Models.CatalogoUsuarioViewModel usuarioViewModel = ObtenerUsuarioViewModel();

            TempData["Mensaje"] = mensaje;

            return RedirectToAction("Index",usuarioViewModel);
        }

        [HttpPost]
        public ActionResult CambiarUsuarioDominio(Models.CatalogoUsuarioViewModel usuario)
        {
            string mensaje = "";
            try
            {
                if (String.IsNullOrEmpty(usuario.ContaseniaAnteriorCambioDominio))
                {
                    usuario.ContaseniaAnteriorCambioDominio = "";
                }

                STPIntegral.Negocios.UsuariosController.ActualizarNombreUsuarioDominio(usuario.IdUsuario, usuario.ContaseniaAnteriorCambioDominio, usuario.UsuarioDominio);
                mensaje = "Se ha modificado correctamente el dominio del usuario";
            }
            catch (ShowCaseException ex)
            {
                mensaje = String.Format("Ocurrio el siguiente error al actualizar: {0}",ex.Message);
            }
            catch (System.Exception ex)
            {
                mensaje = String.Format("Ocurrio el siguiente error al actualizar: {0}", ex.Message);
            }

            Models.CatalogoUsuarioViewModel usuarioViewModel = ObtenerUsuarioViewModel();

            TempData["Mensaje"] = mensaje;

            return RedirectToAction("Index", usuarioViewModel);
        }
    }
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="es-mx">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="icon" type="image/gif" href="@Url.Content("~/Content/images/favicon.gif")" />

    <title>@ViewBag.Title</title>
    
    <link href="@Url.Content("~/Content/modern.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/modern-responsive.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/estilos.css")" rel="stylesheet" />    
    <link href="@Url.Content("~/Content/themes/base/jquery-ui-1.8.16.custom.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/metro-bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/themes/jquery.tagit.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/koGrid/KoGrid.css")" rel="stylesheet" type="text/css" />
    
    <script type="text/javascript">var rootDir = "@Url.Content("~/")"; </script>
    <script type="text/javascript" data-main="@Url.Content("~/scripts/main")" src="@Url.Content("~/scripts/require-jquery.js")"></script>
</head>

<body>

    <div class="page">
        
        <div id="page-header">
            
            <img src="~/Content/images/layout/header-left.png"/>    
            
            <img style="float:right" src="~/Content/images/layout/header-right.png"/>
            
        </div>

        @Html.Partial("navegacion")

        @Html.Action("InfoUsuario", "LogOn")
 
        <div class="page-region">
            <div class="page-region-content">

                <label id="mensaje-version-navegador" class="border-color-red" style="display:none;">Este sistema requiere la version 9 del Internet Explorer, se detecto que su navegador es una version anterior, se recomienda actualizarlo para poder usar el sistema</label>

                @RenderBody()

            </div>
        </div>

    </div>

    <script type="text/javascript">

        $(document).ready(function ()
        {
            if ($.browser.msie == true && parseInt($.browser.version, 10) < 9)
            {
                $("#mensaje-version-navegador").show();
            }
        });
        

    </script>

</body>

</html>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Shared/menuUsuarios.cshtml
@model SolicitudIntegralMVC.Models.UserLogon

@{
    Layout = null;
}

@if (HttpContext.Current.User.Identity.Name != "" && Model != null)
{ 
<li data-role="dropdown">
    <a href="#"> <span title="@Model.DescripcionActivoActual">Rol: @Model.PermisoUsuarioActual</span></a>
    <ul class="dropdown-menu" style="width: auto">
        @foreach (SolicitudIntegralMVC.Models.PermisosSubdivisionesDisponiblesUsuario permiso in Model.ListadoPermisosSubdivisionesDisponibles)
        {
            if (permiso.IdPermisoUa != Model.IdPermisoUaActual)
            { 
            <li>
                <a href="~/LogOn/CambiarPermiso/@permiso.IdPermisoUa"><span title="@permiso.DescripcionSubdivision"> @permiso.Permiso [@permiso.Subdivision] </span></a> 
            </li>
            }
        }
    </ul>
</li>
}
else
{ 
    <li>@Html.ActionLink("LogIn", "Index", "LogOn", new { Area = "" }, new { })</li>
}

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Shared/navegacion.cshtml
<div class="nav-bar">
    
    <div class="nav-bar-inner">
 
        @*<span class="element"><strong>Sistema de Solicitudes Integrales</strong></span>*@
 
        <span class="divider"></span>
 
        <ul class="menu">
                        
            <li>@Html.ActionLink("Inicio", "Index", "Home", new { Area = "" }, new { })</li>

            <li>@Html.ActionLink("Adm.Cta.Usuario", "Index", "Usuarios", new { Area = "" }, new { })</li>

            <li data-role="dropdown">
                <a href="#">Sol. Integrales</a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Listado Solicitudes", "Listado", "SolicitudIntegral")</li>
                    <li>@Html.ActionLink("Nueva Solicitud Integral", "Editar", "SolicitudIntegral")</li>
                    <li>@Html.ActionLink("Listado Folios de Visita", "Listado", "FoliosVisita")</li>

                </ul>
            </li>

            <li data-role="dropdown">
                <a href="#">Sol. Terrestres</a>
                <ul class="dropdown-menu">
                    <li><a href="~/WebTransporteTerrestre/Solicitudterrestre/SolicitudTerrestre.aspx">Nueva Solicitud Terrestre</a></li>
                    <li><a href="~/WebTransporteTerrestre/Solicitudterrestre/Solicitudes.aspx">Administración de Solicitudes</a></li>
                </ul>
            </li>

            <li class="divider"></li>

            @Html.Action("MenuUsuarioNavegacion", "LogOn")

            @Html.Action("MenuNodosAtencion", "LogOn")

            @*@Html.ActionLink("Firma Electronica Ejemplo", "Index", "FirmaElectronica")*@
            
        </ul>

        <span style="text-align:right; float: right;">
            @using (Html.BeginForm("LogOut", "LogOn", new { area = "" }, FormMethod.Post))
            { 
                <input type="submit" class="bg-color-red" style="padding: 2px; margin: 2px 13px 0 0; height: auto;" value="Cerrar Sesión" />
            }
        </span>

    </div>

</div>

SolicitudIntegralSVN/SolicitudIntegralMVC/SolicitudIntegralMVC/Views/Shared/nodosAtencion.cshtml
@model SolicitudIntegralMVC.Models.UserLogon

@{
    Layout = null;
}

@if (HttpContext.Current.User.Identity.Name != "" && Model != null)
{ 
<li data-role="dropdown">
    <a href="#"> <span title="Nodo Atención actual: @Model.NodoAtencionActual">Nodo Atencion: @Model.NodoAtencionActual</span></a>
    <ul class="dropdown-menu" style="width: auto">
        @foreach (STPIntegral.Datos.stp_c_nodos nodo in Model.NodosAtencion)
        {
            if (nodo.cve_nodo != Model.NodoAtencionActual)
            { 
            <li>
                <a href="~/LogOn/CambiarNodo/@nodo.cve_nodo"><span title="@nodo.cve_nodo"> [@nodo.cve_nodo] @nodo.des_nodo</span></a> 
            </li>
            }
        }
    </ul>
</li>
}
else
{ 
    <li>@Html.ActionLink("LogIn", "Index", "LogOn", new { Area = "" }, new { })</li>
}